# @package habitat.simulator.agents.spot_agent
defaults:
  - /habitat/simulator/sim_sensors@sim_sensors.jaw_rgb_sensor: jaw_rgb_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.jaw_panoptic_sensor: jaw_panoptic_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.third_rgb_sensor: third_rgb_sensor

sim_sensors:
  jaw_rgb_sensor:
    height: 480
    width: 640
    hfov: 90
  jaw_panoptic_sensor:
    height: 480
    width: 640
    hfov: 90